### ISSUE TITLE
HA 2023.9.0b0 -Unhandled promise rejection

### ISSUE THREAD

**Issue by Anto79-ops** [htmltiger/numberbox-card#100]
hey, 

looks like some changes in HA 2023.9.0 are creating error logs.

```
2023-08-31 12:59:18.184 ERROR (MainThread) [frontend.js.latest.202308310] Unhandled promise rejection from Chrome WebView 114.0.5735.220 on Android 9
"http://192.168.1.81:8123/hacsfiles/numberbox-card/numberbox-card.js?hacstag=304967918414"
```

thanks

**Comment by htmltiger** [comment]
hope this is fixed now

**Comment by Anto79-ops** [comment]
thanks. During the end of that beta, they actually suppressed the logging of this error because there was some core frontend integrations that were also giving these errors, so they reverted the the logging this error, temporarily. BUT, the error still exist just we cannot see it via logging. I won't know if your new fix will resolve this until they bring back the logging for these types of errors :)
