### ISSUE TITLE
[Feature Request] Provide 'decimals' parameter

### ISSUE THREAD

**Issue by mathieu-mp** [htmltiger/numberbox-card#25]
Nice and useful work, thank you @htmltiger !

Would you provide a 'decimals' parameter, to specify the exact number of decimals to show ?
It would prevent decimal number to be displayed as integers (e.g. 15.9 ... 16 ... 16.1 would become 15.9 ... 16.0 ... 16.1)

**Comment by htmltiger** [comment]
have you tried this?
```step: 0.1```

https://www.home-assistant.io/integrations/input_number/

**Comment by mathieu-mp** [comment]
It works great ! I were just mislead by some inconsistencies I had in my configuration.
Thanks for your fast answer !
