### ISSUE TITLE
Option "initial" not working

### ISSUE THREAD

**Issue by srodighiero** [htmltiger/numberbox-card#31]
Often the card report starting nr as "0" instead of what the entity require (60) and what setup on the card itself as "initial", resulting in not having the possibility to set any number

![image](https://user-images.githubusercontent.com/4833164/151190043-6833dbd4-0647-4b77-ba04-4191d80b849a.png)

**Comment by htmltiger** [comment]
What is the `min` setup on your `number` entity in `configuration.yaml`? post it here so i can replicate it to check.

Remember that numberbox will only change the entity if you press + or - button,

It will not send/change to initial itself, also it will display any number it receives.

Can you please post the state and attributes of your number entity from `Developer Tools > States` when you get this issue?

**Comment by srodighiero** [comment]
At this point is probably a problem on the integration itself, you are right, as you can see from the developer page:
![image](https://user-images.githubusercontent.com/4833164/151780872-dd5f978b-33c0-46ad-94e2-258e60c5c56b.png)
