### ISSUE TITLE
FR: add domain config

### ISSUE THREAD

**Issue by binzhou** [htmltiger/numberbox-card#33]
currently the service assumes the domain matches the domain of the entity. However, this means custom services cannot be used.

I'd like to use the izone.airflow_max service (https://www.home-assistant.io/integrations/izone/#service-izoneairflow_max) but the entity has a climate domain. It would be great to be able to configure the domain for the service call (or alternatively, not auto-populate the domain in the case that a full service name is provided eg. "izone.airflow_max" shouldn't customize the domain, whereas "airflow_max" could use an inferred domain from the entity.

**Comment by htmltiger** [comment]
added in 3.4
