### ISSUE TITLE
Support for language-specific formatting

### ISSUE THREAD

**Issue by dodekaphilist** [htmltiger/numberbox-card#36]
It would be nice if the card could support language-specific formatting, like HA is doing since v0.118 (see [here](https://github.com/home-assistant/frontend/pull/7516)) for a better integration into the system. Thanks! 🙂

**Comment by htmltiger** [comment]
added, please try new version.

**Comment by dodekaphilist** [comment]
I now have the correct decimal symbol, thanks!
However, somewhere within the process the trailing 0 got lost and it's now displayed as e.g. 18 insted of 18,0 (before, trailing zeros were always shown)

**Comment by htmltiger** [comment]
3.6 should fix it
