### ISSUE TITLE
Wait time for physical devices

### ISSUE THREAD

**Issue by dodekaphilist** [htmltiger/numberbox-card#38]
I already decribed this issue in #24 and I want to address this again in this issue.

The problem is probably an issue a lot of physical devices are facing. When setting a new value, it takes some time to get into effect on the device. In my case I saw, that after the shown value switches from the new value in red back to the original value in black, before this value updates to the actual value.

![numberbox](https://user-images.githubusercontent.com/31287077/152878347-bab76507-88aa-42ce-a616-16e9885070c6.gif)

HA does fix this by waiting for the value to get updated before changing the font color back to normal.

![HA-thermostat](https://user-images.githubusercontent.com/31287077/152878358-853fddb0-6542-43ca-a9bb-c1240b9656c3.gif)

A solution could be to introduce a wait time config item, but maybe there is a better way where the user doesn't have to do this manually. Idk how HA solves this

Thanks! 🙂

**Comment by htmltiger** [comment]
3.6 should fix this, please try it

**Comment by dodekaphilist** [comment]
Works flawlessly, thank you ❤️
