### ISSUE TITLE
Feature Request: Add formatting options for unit: time

### ISSUE THREAD

**Issue by clau-bucur** [htmltiger/numberbox-card#48]
Please consider adding a way to format the value when using "unit: time" option.
Currently it's dynamic, going from "mm:ss" to "hh:mm:ss" depending on the entity value.
However, there are cases when one would need to stick to "hh:mm", for example, and not care about setting seconds.

One use case is with the new support for input date time helper, when you might not really care about setting seconds (as HA's default behavior).

Thank you!

**Comment by andjones132** [comment]
First, thank you for developing this card. It is very useful and improves on the standard input options. I would second this request for input_datetime entities. I have no reason to display the seconds as this control is only used to set the time in hours and minutes. Also, it would be nice to have the ability to display the time in 12 hour format with AM/PM, but I understand this maybe hard to do giving the current design. However, formatting the time as %H:%S would be very nice.

**Comment by htmltiger** [comment]
added "timehm" option for hh:mm in 3.14
