### ISSUE TITLE
Increase size of "plus" and "minus" signs

### ISSUE THREAD

**Issue by Protoncek** [htmltiger/numberbox-card#66]
I didn't find anywhere... is it possible to increase up7down icons? I can increase size of value, but i'd also like to have bigger + and - signs... (or icons which replaces them).

**Comment by ildar170975** [comment]
This is not an issue for `numberbox-card` - neither a bug nor a FR, this is just a question and probably should be asked in the Community first.
Use card-mod to style the card's elements:
https://community.home-assistant.io/t/card-mod-add-css-styles-to-any-lovelace-card/120744/2416?u=ildar_gabdullin

**Comment by Protoncek** [comment]
Thanks! I did search there, but find appropriate thing between over 3800 posts is.. well, i guess i'd win a lottery sooner...
I agree, it's not a bug, but it could be FR, since changing size is more or less a basic function. By default both signs and value are way too close positioned, so it's hard to press them if card is not big.

**Comment by htmltiger** [comment]
you can use scale to change the size.
```
.cur-box ha-icon{ transform:scale(2); }
```

**Comment by ildar170975** [comment]
> but find appropriate thing between over 3800 posts is.. well, i guess i'd win a lottery sooner

No need, go to card-mod community thread -> 1st post -> link at the bottom
