### ISSUE TITLE
Value(s) updated by automation are not consistently updated on screen

### ISSUE THREAD

**Issue by BramWarrick** [htmltiger/numberbox-card#67]
This one threw me for a loop and I lost some time to triple and quadruple checking logical operators, etc.

In the end, what I learned is that my logic was working - but the numberbox-card wasn't updating.

Here's the concept:
For a variety of uses, I enforce a number gap in a user configurable range. 
An easy example would be that the target (nighttime) low temp should always be at least 3° F below the high end of the range. When someone pushes the low up, it's evaluated against the high, and if the high is now lower than the (low + 3)...  the high is set to the (low + 3).

I do this with any user configurable sets of ranges. It's just basic UI kind of stuff.

When these updates occur in HA, they do not consistently update in the numberbox-card. I've looked in the automation and I see that the values are updated correctly. I open another tab and look at the same page and the numbers are updated. Same applies to refreshing the page. I added a vanilla entity card to the same panel - and it is consistently updated without intervention (and timely in its updates).

But the numberbox-card will not _consistently_ pick up the update. Sometimes yes, sometimes no. But I love the design and I don't want to drop numberbox-card from my set up - it's key to many screens. I'm relatively certain this used to work consistently - some of what I describe has been present for _months_ and it was well tested.

If you're curious about what my automation does, it just looks at a low value for a range and if it's getting to close to the next higher value, it pushes the next higher value up by 1 - enforcing a minimum gap and preventing a low from exceeding the high. It does the same thing in reverse if the high is being lowered. Fundamental number hygiene stuff.

My logic works - I have both cards on my screen. Entity updates; numberbox-card is hit and miss.

I used to write python, but that was years ago. Beyond describing the issue, I'm not sure how to be the most help.

Thank you for your time - and I hope you're having a good holiday season.

**Comment by RipZ** [comment]
same here

**Comment by skortela** [comment]
Same here.
When viewing numberbox card using different devices, some of those gives different/outdated results.

**Comment by htmltiger** [comment]
> Here's the concept: For a variety of uses, I enforce a number gap in a user configurable range...

I have fixed a bug where step_entity was missing updates, please try 4.5

**Comment by htmltiger** [comment]
I have updated it a little, possibly fix the above issue,
In the version 4.8 please add `refresh: 1` in the config and see if that helps.
