### ISSUE TITLE
Uncaught SyntaxError: Unexpected token '<'

### ISSUE THREAD

**Issue by laplug** [htmltiger/numberbox-card#68]
Hi,
I get the following error with numberbox-card:
```
Logger: frontend.js.latest.202211080
Source: components/system_log/__init__.py:256
First occurred: 00:48:52 (2 occurrences)
Last logged: 13:19:03

http://homeassistant.local:8123/local/numberbox-card.js:8:1 Uncaught SyntaxError: Unexpected token '<'
```
Hass version:
```
Home Assistant 2022.11.5
Supervisor 2022.11.2
Operating System 9.3
Frontend 20221108.0 - latest

```
In the logs I found:
```
2022-12-03 00:48:52.774 ERROR (MainThread) [frontend.js.latest.202211080] http://homeassistant.local:8123/local/numberbox-card.js:8:1 Uncaught SyntaxError: Unexpected token '<'
2022-12-03 13:19:03.992 ERROR (MainThread) [frontend.js.latest.202211080] http://homeassistant.local:8123/local/numberbox-card.js:8:1 Uncaught SyntaxError: Unexpected token '<'
```
I use the card vanilla, so it seems to me something in the code of numberbox-card. However, I didn't find any references from other users about this problem.

**Comment by htmltiger** [comment]
does your numberbox-card.js line 8 contains '<' ?
how did you install it?

**Comment by laplug** [comment]
Oops... I found a leftover file with the same filename in www, with HTML code.
Thanks for your hint about line 8, it made me look further than the .js file.
Sorry and have a nice day!
