### ISSUE TITLE
Number formatting settings are not being used

### ISSUE THREAD

**Issue by ascha191** [htmltiger/numberbox-card#69]
In the profile settings, a number format has been selected which uses a '.' as a decimal separator.
![image](https://user-images.githubusercontent.com/99959910/211196668-21451255-a177-41a9-937f-790d350ca6d5.png)
All of the components I am using are also using the correct format, except for the numberbox card which is using a ',' instead of a '.'.
![image](https://user-images.githubusercontent.com/99959910/211196830-89bccf99-5681-4db0-a3a8-ecbf3ae4ae96.png)

**Comment by htmltiger** [comment]
Please try 4.2

**Comment by ascha191** [comment]
worked. Thanks very much!
