### ISSUE TITLE
Any way to alter the icon colour based on a state?

### ISSUE THREAD

**Issue by richsimpson** [htmltiger/numberbox-card#71]
So I am using in a climate style, and Woudl be great to have the icon change colour based on the state of something.

This is what I have:
![image](https://user-images.githubusercontent.com/51749826/211540738-ef95307e-a020-43ae-a52b-eb8950bf37ef.png)

A different template card I wrote uses this code to do it :
![image](https://user-images.githubusercontent.com/51749826/211540866-3519ade6-e2c1-4416-a334-ea1d2291734d.png)

Great work though, really handy card to use on my dashboard.

**Comment by ildar170975** [comment]
Can be achieved by card-mod.

**Comment by richsimpson** [comment]
> Can be achieved by card-mod.

Thanks, got it working:
![image](https://user-images.githubusercontent.com/51749826/211933591-d5f20793-fe14-4338-b4ca-33bae91818bf.png)


this was my code - just incase it helps anyone in future - entities all unique to me obviously:
type: entities
entities:
  - type: custom:numberbox-card
    entity: input_number.office_required_temperature
    name: Office
    icon: mdi:thermostat
    card_mod:
      style: |
        :host {
           --paper-item-icon-color:
           {% if states('climate.radiator_office') == 'off' %}
              skyblue; {% elif states('climate.radiator_office') == 'heat' %}
              orange;
           {% endif %}
          }
    service: input_number.set_value
    min: 10
    max: 25
    step: 0.5
    secondary_info: >
      Actual Temp:<b style="color:green"> %sensor.office_current_temp:state
      </b><br /> Target Temp:<b style="color:red">
      %input_number.office_required_temperature:state </b><br />  Heating
      State:<b style="color:orange"> %climate.radiator_office:state </b><br />
