### ISSUE TITLE
compare values in secondary_info

### ISSUE THREAD

**Issue by MrThiemann** [htmltiger/numberbox-card#74]
Hey,

can someone explain to me how I can compare two values ​​in secondary_Info?

i have a sensor (sensor.Test ) and a helper (input_number.test).  

if both are the same then ok if different then xxx

somehow I can't get it to use an if is_state template here.

**Comment by htmltiger** [comment]
It is possible by creating a template sensor
https://www.home-assistant.io/integrations/template/
```yaml
template:
  - sensor:
      - name: "Sun State"
        state: >
          {% if is_state('sun.sun', 'above_horizon') %}
            up
          {% else %}
            down
          {% endif %}
```
