### ISSUE TITLE
Display number breaks when returning to previous value

### ISSUE THREAD

**Issue by alrzbv** [htmltiger/numberbox-card#75]
Hello, thank you very much for your work!
Problem:
When returning to the previous value, the displayed value breaks:
1. stays "red" until page refresh
2. does not refresh (until delay expires) when the values are changed later

![numberbox_card](https://user-images.githubusercontent.com/30652363/221006265-be897462-e4ec-4f44-8e1d-c033d1588d8d.gif)

Simple configuration entity:
```
type: custom:numberbox-card
border: true
entity: input_number.spalnia_okno_vremia_ruchnogo_otkrytiia
name: qwe
```

**Comment by htmltiger** [comment]
Please try the update 4.4
