### ISSUE TITLE
Need multiple service parameters

### ISSUE THREAD

**Issue by uSlackr** [htmltiger/numberbox-card#82]
For my use case, I need to be able to specify three other parameters in addition to the value of the card.  is there a way to accomplish this?

**Comment by ildar170975** [comment]
Could you elaborate?

**Comment by htmltiger** [comment]
It can be possible with a small update.
Will the other service parameters fixed or status of another entity?

**Comment by uSlackr** [comment]
> Could you elaborate?

My use case involves using 15 of these to control 15 modbus devices. In addition to the value, I need to pass identifier and other parameters specific to the instance.

**Comment by uSlackr** [comment]
They would be fixed per card instance (as I see it now)

**Comment by uSlackr** [comment]
Thanks for this!!!
