### ISSUE TITLE
Add option to type in number

### ISSUE THREAD

**Issue by Cadair** [htmltiger/numberbox-card#85]
Hello! Thanks for the awesome card.

I have one suggestion which would help me out with my use case, it would be nice to be able to directly type the number in. Maybe if you click the number it could go to text input?

**Comment by ildar170975** [comment]
Tapping on a row opens a more-info window where you can edit the value.

**Comment by Cadair** [comment]
The more info window for me just shows the standard hass slider UI for editing the number?

**Comment by ildar170975** [comment]
Because you initially created this input number helper as a slider.

**Comment by Cadair** [comment]
oh nice, didn't know that option existed. Thanks.
