### ISSUE TITLE
Value-Rounding not possible when using cloudflared

### ISSUE THREAD

**Issue by pos-ei-don** [htmltiger/numberbox-card#97]
I am using 
https://github.com/htmltiger/numberbox-card/issues/94

and i am not using cloudflaire as a plugin, as someone mentioned there in 
https://github.com/htmltiger/numberbox-card/issues/94#issuecomment-1646965241

I use it as cloudflaired VPN connector.

The problem i see is that when accessing HA directly via IP, the "state:~1" parameter works perfectly.
When accessing it ober the Cloudflaire-VPN tunnel, "custom:numberbox-card" stays empty and does not display anything.

**Comment by htmltiger** [comment]
Caching issues.

Check loaded version in developer tools console in chrome

**Comment by pos-ei-don** [comment]
I don't think so. 
> NUMBERBOX_CARD 4.12
I also hit STRG+F5. 
Also tried private mode.

But i get;
> Uncaught (in promise) TypeError: b.toFixed is not a function
>     at NumberBox.secondaryInfo (numberbox-card.js?hacstag=304967918413:112:51)
>     at NumberBox.render (numberbox-card.js?hacstag=304967918413:55:12)
>     at NumberBox.update (lit-element.ts:160:24)
>     at NumberBox.performUpdate (reactive-element.ts:1331:14)
>     at NumberBox.scheduleUpdate (reactive-element.ts:1263:17)
>     at NumberBox._$Ej (reactive-element.ts:1235:25)

Can this help`?

**Comment by htmltiger** [comment]
4.13 is the new version

**Comment by pos-ei-don** [comment]
Thank you. Cannot find a way to clear the cloudflaire cache. Will wait...
